### ISSUE TITLE
How to safely repeat chain links

### ISSUE THREAD

**Issue by takaaptech** [airstruck/knife#6]
I am here, sorry for bothering you again, how to safely repeat chain actions:
For example, if we set chain repeat to true, this code:
```lua
Chain(
    TimedText(1, 'fading in'),
    TimedText(1, 'showing splash screen'),
    TimedText(1, 'showing title screen'),
    TimedText(1, 'showing demo')
)()
```
Will print 
fading in
showing splash screen
showing title screen
showing demo

and then continue 

fading in
showing splash screen
showing title screen
showing demo

Until some flag is turn on or off

Thank so much!

**Comment by airstruck** [comment]
You're not bothering me at all! I'm glad you're getting some use out of it; these questions help me figure out what needs better documentation.

You can do something like this:

```lua
local doStuff = Chain(
    TimedText(1, 'fading in'),
    TimedText(1, 'showing splash screen'),
    TimedText(1, 'showing title screen'),
    TimedText(1, 'showing demo')
)
```

Notice the variable assignment at the beginning, and no `()` at the end. Now `doStuff` holds a function that runs the chain, so you can call `doStuff()` to run it (as many times as you like).

Now, another feature of Chain is that a "link" (one of the functions in a chain) can return a "chain" (like `doStuff` in this example) instead of calling `go`. This is documented, but it's easy to miss. In other words, if you wanted it to keep running forever, you should be able to do something like this:

```lua
local doStuff
doStuff = Chain(
    TimedText(1, 'fading in'),
    TimedText(1, 'showing splash screen'),
    TimedText(1, 'showing title screen'),
    TimedText(1, 'showing demo'),
    function () return doStuff end
)
```

Now all you need to do is put a condition around `return doStuff`, and only return it when your condition is met. When you don't return it, the chain will stop repeating.

Please let me know if that didn't make sense or didn't work properly. Good luck!

**Comment by takaaptech** [comment]
I think we miss some params here. It runs only one time:
```lua
local function move(go)
	-- body
	print("move ")
	print("and then.. after some wait")
	go()
end

local function scale(go)
	-- body
	print("scale ")
	print("and then .. after some wait")
	go()
end

--local should_repeat = true

local doStuff
doStuff = Chain(
	scale,
	move,
    function ()
		return doStuff
	end
)

doStuff()

```

if i change return doStuff to return doStuff() , it runs and seem to be repeat but then it is error stack over flow?

**Comment by airstruck** [comment]
You're right, I forgot how that feature was supposed to work, it's for something different. Sorry, it's late here!

Does it still overflow if you do this: `function () doStuff() end` without the `return`?

**Comment by takaaptech** [comment]
@airstruck Just go to sleep. We will see it running tomorrow!

**Comment by airstruck** [comment]
Alright, after getting some sleep and messing with it for a little while, I'm remembering why this is a tough problem. Restarting a chain from within a chain would ideally look like `function () doStuff() end`, like we talked about. The problem with that is the recursion will eventually overflow the call stack, as you found out. There are two possible ways around that.

One solution is making Chain tail-recursive, which could be possible. But that also means that user code (calling `go`) would have to be tail-recursive, which I think would be too limiting and too easy to mess up. It might also damage performance on LuaJIT, ironically.

Another possible solution is making Chain iterative instead of recursive, which would require a complete rewrite and probably quite a bit more code. I want to avoid that if possible.

Now, here's the good news. If anything in the chain is actually _asynchronous_, as it usually would be in "real code," you'll be breaking the call stack and you won't run into the stack overflow, and the `function () doStuff() end` thing should Just Work™. In other words, if you pass `go` to a timer callback or something similar in any of the "links," you should be alright. I think.

If it's _not_ asynchronous, like your test, you can just do this:

```lua
local doStuff = Chain(something, something_else)
while condition do doStuff() end
```

Let me know if this works for you; if not we'll figure something else out.

**Comment by takaaptech** [comment]
@airstruck , Volla! If we put it in real world as you comment, it works like a charm! Thank you so much. And base on code that you teach me before, i can write Repeat function for naturally code. Can you review it? 
```lua
local function Repeat( ... )
	-- body
	local doStuff = Chain()
	local t = { ... }
	for _, func in ipairs(t) do
		doStuff = doStuff(func)
	end

	doStuff = doStuff(
	    function ()
			return doStuff()
		end
	)
	return doStuff
end

local action = Repeat(move1,move2)

action()

```

Just tested and it works, I have an enemy patrol now 💃 , need your review. Thank so much!

**Comment by airstruck** [comment]
You should be able to simplify it to this:

```lua
local function Repeat( ... )
    local doStuff
    doStuff = Chain(...)(function () doStuff() end)
    return doStuff
end

local action = Repeat(move1,move2)

action()
```

How will you stop it from repeating, though? I predict issue #6 will be "add a way to cancel chains" ;)

**Comment by takaaptech** [comment]
@airstruck Ha ha like your issue title 
How about this:
```lua
local function Repeat( ... )
    local doStuff = {should_stop = false}
    
    doStuff.stop = function ( ... )
    	-- body
    	doStuff.should_stop = true
    end

    doStuff.run = Chain(...)(function ()
    	if not doStuff.should_stop then
    		doStuff.run()
    	end
    end)
    return doStuff
end

-- local action = Repeat(move1,move2)

-- action()


local action = Repeat(m1,m2)

action.run()

timer.performWithDelay(5000, function ( ... )
	-- body
	action.stop()

end)
```

**Comment by airstruck** [comment]
Nice! Good luck on your game, I hope to see it when it's ready :+1:

**Comment by takaaptech** [comment]
Thank so much @airstruck !
