### ISSUE TITLE
Chaining Chains

### ISSUE THREAD

**Issue by coltonoscopy** [airstruck/knife#8]
Hey airstruck! Your library is great; I've successfully used Chain mixed with Timer.tween to get a bunch of sprites autonomously moving around a grid-based map, and the code for it is fairly clean and compact. However, I now want those sprites to be able to move along their path one at a time, waiting for the one prior to finish before moving on, and for this I figured I could just Chain some Chains (the Chains I'm currently using are effectively just movement tweens and take place concurrently, so chaining them would accomplish this). The documentation suggests that Chains can take either standard go-function links or other Chain objects as arguments, but this doesn't seem to be working in my code; everything is staying still. Here's a gist in case this may prove helpful; I'm sure I'm just using the library wrong! Thanks for taking a look!

https://gist.github.com/coltonoscopy/7475bcd4ad3892641d6c348816cb09fd

**Comment by airstruck** [comment]
Hello, glad to see Chain getting some use!

> The documentation suggests that Chains can take either standard go-function links or other Chain objects as arguments, but this doesn't seem to be working in my code

Well, they can, but it might not work quite like you expect. You're probably thinking of the part of the readme that talks about link functions either calling "go" or returning a chain, which is for something a bit different (i.e. if you wanted to create a library that returns chains instead of taking callbacks, like you might return a Promise in JS).

Chain returns a function. That function can do two different things. When you call that function with no arguments or an initial nil, it executes the chain. But you can also call it with a link function as an argument; in that case it adds that link to the chain instead of executing the chain.

So, if you add chain B to chain A as a link function, when A calls B it will pass in the "go" function that Chain generates. Because of that, the "go" function is appended to chain B as a link, instead of chain B being executed as it would if it were called with no arguments.

What you need might look something like:

```lua
chainA = Chain(aLinkFunc) -- chain A does something
chainB = Chain(anotherLinkFunc) -- chain B does something else
-- chain A kicks off chain B when it's done
chainA(function(go) chainB(); go() end)
-- run chain A
chainA()
```

By the way, because of this instead of packing and unpacking a table, you can create the chain up front and then call the returned function as many times as you like, passing each next link in the chain, and then call it with no arguments when you're done. You should also be able to safely add links to a chain on the fly while it's already running.

Hope this helps, give it a try and let me know if you run into anything. There are two closed issues that discuss sort of similar things, those might also interest you.

**Comment by coltonoscopy** [comment]
Hi airstruck,

Thanks for your reply! I've gone ahead and updated the gist, using what you said about creating the Chain instance and then appending functions to that instead of unpacking tables (looks quite a bit nicer, so thanks for the tip)!

In the `attemptPath` function, I added this:

```lua
-- export movement chain so it can be chained with others later
return function(go)
    pathChain()
    go()
end
```

Before I was just returning the Chain function after unpacking everything, but it didn't fit the go paradigm that links are supposed to have to operate; now, it's being called before `go()`, which should kick it off when executed as a link in another Chain.

Indeed, it seems that things are moving again, but all of the links (paths) execute simultaneously instead of being sequential, which is the intended behavior. Also peculiar is that if Line 78 isn't commented out, things go kind of crazy and everything moves super fast, which leads me to think that `self.entitiesMoving` is being set to `false` right away and not being deferred to the end of the Chain's execution, which is the goal, it being added as a link after all of the paths are added in Lines 73-76.

Is there perhaps something still awry with the way I've structured things, if not in the `TweenMovement` function, perhaps? Thanks so much for taking the time to look at this! If you notice anything else from an engineering/layout/style perspective that you would streamline or change too, I'd love to hear that! :)

**Comment by airstruck** [comment]
I think this will do what you want:

    return function()
        moveChain()
        return moveChain
    end

By returning another chain, you effectively schedule the rest of the links in the current chain to run after the other chain runs. As long as moveChain is asynchronous, it should work. Let me know if it doesn't.

> If you notice anything else from an engineering/layout/style perspective that you would streamline or change too, I'd love to hear that! :)

Is your project on GitHub? I'd want to get a look at the whole thing for context. My initial reaction is "too many closures," but that's a little hypocritical (check out Chain's source).

**Comment by coltonoscopy** [comment]
Hey airstruck,

Wow, so that did work! And that fixed the issue with the `entitiesMoving` bit as well. So this is effectively just linking the Chains themselves rather than functions that call the Chains and then `go`; since I was linking `go`-functions that were simply calling the Chains before, I assume they all just executed very fast synchronously, thus executing concurrently rather than sequentially and with dependent behavior; the Chains I take it don't resolve as links until after they have completely finished running, and `go` is thereby passed and executed implicitly?

Also, here's the source for the project if you'd like to take a look:
https://github.com/coltonoscopy/battle-engine

Thank you so much for your time and help! This library is great!

**Comment by airstruck** [comment]
> the Chains I take it don't resolve as links until after they have completely finished running, and go is thereby passed and executed implicitly?

Something like that; `go` is basically nothing more than "execute the next link in the chain," so if you manage to stick more links in there before it fires, it should work out.

Incidentally I think this ought to work too:

    return function(go)
        moveChain(go)()
    end

Will take a look at your project this weekend and see if I can offer anything useful :)

**Comment by coltonoscopy** [comment]
Yep, that worked as well! And I can always get down with fewer lines :) I may have to keep writing code like this to get a full proper grasp of everything, but I think this is a great foundation for future asynchronous code. And imo this lib makes it look really nice, as well as easy.

And that would be amazing! You have a knack for distilling down code, which is something I try and strive for, so I look forward to seeing what you offer!
